In [2]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables. 

In [3]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
for element in list_:
    print("Data type of element in list_:", type(element))
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)  Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list. Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object=list_, dtype=int)

print("Data types in list_:")
for element in list_:
    print(type(element))
print("\nData types in array_list:")
for element in array_list:
    print(type(element))

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [ ]:
# Q4. Write a code to find the following characteristics of variable, num_array: 
(i) shape
(ii) size

In [6]:
import numpy as np

num_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

shape = num_array.shape
print("Shape of num_array:", shape)

size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (3, 3)
Size of num_array: 9


In [ ]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. 
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [7]:
import numpy as np

# Creating a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print("3x3 Matrix of Zeros:")
print(zero_matrix)

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
